# Generated by Django 5.0 on 2023-12-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0002_districtrate_markets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districtrate',
            old_name='price',
            new_name='max_price',
        ),
        migrations.AddField(
            model_name='districtrate',
            name='min_price',
            field=models.FloatField(default=0),
        ),
    ]
