# Generated by Django 5.0 on 2023-12-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farm_name',
            field=models.CharField(default='My Farm', max_length=100),
        ),
        migrations.AddField(
            model_name='farm',
            name='size_acres',
            field=models.FloatField(null=True),
        ),
    ]
