# Generated by Django 5.0 on 2023-12-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_farm_farm_name_farm_size_acres'),
    ]

    operations = [
        migrations.AddField(
            model_name='landconditions',
            name='evapotrans',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='landconditions',
            name='soilmoisture',
            field=models.FloatField(null=True),
        ),
    ]
