# Generated by Django 5.0 on 2023-12-17 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_landconditions_evapotrans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landconditions',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='landconditions',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm'),
        ),
    ]
