# Generated by Django 5.0 on 2023-12-17 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_alter_landconditions_soil_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landconditions',
            name='leafcover',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='landconditions',
            name='lst',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(150), django.core.validators.MaxValueValidator(1310)]),
        ),
        migrations.AlterField(
            model_name='landconditions',
            name='ndvi',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='landconditions',
            name='nitrogen',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='landconditions',
            name='phosphorus',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='landconditions',
            name='potassium',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='landconditions',
            name='soil_ph',
            field=models.FloatField(null=True),
        ),
    ]
