# Generated by Django 5.0 on 2023-12-17 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_alter_landconditions_leafcover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landconditions',
            name='farm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farms.farm'),
        ),
    ]
