# Generated by Django 5.0 on 2023-12-17 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0007_alter_landconditions_farm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='crops',
        ),
        migrations.CreateModel(
            name='EachFarmCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_date', models.DateField(null=True)),
                ('veg_growth_date', models.DateField(null=True)),
                ('gran_growth_date', models.DateField(null=True)),
                ('ripen_date', models.DateField(null=True)),
                ('harvest_date', models.DateField(null=True)),
                ('crops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.crops')),
                ('farms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
            ],
        ),
    ]
