# Generated by Django 5.0 on 2023-12-18 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0001_initial'),
        ('farms', '0008_remove_farm_crops_eachfarmcrop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='districts.address'),
        ),
    ]
