# Generated by Django 5.0 on 2023-12-19 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0009_alter_farm_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_yield', models.FloatField()),
                ('avg_cost', models.FloatField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.crops')),
            ],
        ),
    ]
