# Generated by Django 5.0 on 2023-12-18 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
        ('farms', '0009_alter_farm_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('nitrogen', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('phosphorus', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('potassium', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FertCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='districts.address')),
            ],
        ),
        migrations.CreateModel(
            name='FertRecc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.crops')),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizers.fertilizers')),
            ],
        ),
        migrations.CreateModel(
            name='FertVendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizers.fertcompany')),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizers.fertilizers')),
            ],
        ),
    ]
