# Generated by Django 5.0 on 2023-12-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrousers',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
